# Gitleaks configuration for RAG platform
# Detects API keys, tokens, and other secrets specific to this project

[extend]
# Use default gitleaks rules as base
useDefault = false

# Custom rules for RAG platform API keys
[[rules]]
id = "rag-tenant-api-key"
description = "RAG Platform Tenant API Key"
regex = '''tenant_[a-z0-9]+_[a-f0-9]{32}'''
keywords = ["tenant_"]

[[rules]]
id = "rag-admin-api-key"
description = "RAG Platform Admin API Key"
regex = '''tenant_admin_[a-f0-9]{32}'''
keywords = ["tenant_admin_"]

[[rules]]
id = "rag-generic-api-key"
description = "Generic API Key Pattern"
regex = '''[a-zA-Z0-9_-]*[aA][pP][iI][_-]?[kK][eE][yY][_-]?[=:]\s*['\"]?[a-zA-Z0-9_-]{16,}['\"]?'''
keywords = ["api_key", "apikey", "API_KEY", "APIKEY"]

[[rules]]
id = "rag-secret-key"
description = "Secret Key Pattern"
regex = '''[a-zA-Z0-9_-]*[sS][eE][cC][rR][eE][tT][_-]?[kK][eE][yY][_-]?[=:]\s*['\"]?[a-zA-Z0-9_-]{16,}['\"]?'''
keywords = ["secret_key", "secretkey", "SECRET_KEY", "SECRETKEY"]

[[rules]]
id = "rag-access-token"
description = "Access Token Pattern"
regex = '''[a-zA-Z0-9_-]*[tT][oO][kK][eE][nN][_-]?[=:]\s*['\"]?[a-zA-Z0-9_-]{20,}['\"]?'''
keywords = ["token", "TOKEN", "access_token", "ACCESS_TOKEN"]

# Database connection strings
[[rules]]
id = "postgres-connection"
description = "PostgreSQL Connection String"
regex = '''postgresql://[a-zA-Z0-9_-]+:[a-zA-Z0-9_@-]+@[a-zA-Z0-9.-]+:[0-9]+/[a-zA-Z0-9_-]+'''
keywords = ["postgresql://", "postgres://"]

# Allowlisted files and patterns
[allowlist]
description = "Allowlisted files and patterns"

# Allow demo and example files
paths = [
    '''.env.example''',
    '''.env.template''',
    '''.env''',
    '''\.claude/.*''',
    '''logs/.*''',
    '''demo_tenant_keys\.json''',
    '''docs/.*''',
    '''QUICK_RAG_DEMO.md''',
    '''test.*\.py''',
    '''tests/.*''',
    '''demo-data/.*''',
    '''.venv/.*''',
    '''src/frontend/node_modules/.*''',
    '''node_modules/.*''',
]

# Allow placeholder/example values
regexes = [
    '''your[_-]?[a-zA-Z0-9]*[_-]?(key|token|secret)[_-]?here''',
    '''replace[_-]?with[_-]?actual''',
    '''example[_-]?[a-zA-Z0-9]*''',
    '''placeholder''',
    '''<[a-zA-Z0-9_-]+>''',
    '''test[_-]?[a-zA-Z0-9]*[_-]?(key|token)''',
    '''mock[_-]?[a-zA-Z0-9]*''',
    '''dummy[_-]?[a-zA-Z0-9]*''',
    # Allow default development database credentials (not production secrets)
    '''postgresql://rag_user:rag_password@.*''',
    '''your_super_secret_key_here''',
    # Allow common development/library placeholder patterns
    '''your-replicate-api-key''',
    '''auto-generated-key''',
    '''.*TokenCallback.*''',
    '''.*CancellationToken.*''',
    '''.*GreaterThanToken.*''',
]

# Allow specific patterns that are safe
stopwords = [
    "your-admin-api-key-here",
    "your-tenant-api-key-here", 
    "test_api_key",
    "mock_key",
    "example_key",
    "placeholder_key",
    "dummy_token",
]