global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rag-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rag-app:8000']
    scrape_interval: 10s

  - job_name: 'rag-db'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rag-db-exporter:9187']

  - job_name: 'rag-vector'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rag-vector:8001']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 